import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:inventaris_toko/data/models/app_settings.dart';
import 'package:inventaris_toko/data/models/category.dart';
import 'package:inventaris_toko/data/models/cost_price_adjustment.dart';
import 'package:inventaris_toko/data/models/product.dart';
import 'package:inventaris_toko/data/models/restock_list.dart';
import 'package:inventaris_toko/data/models/stock_mutation.dart';
import 'package:inventaris_toko/data/repositories/app_settings_repository.dart';
import 'package:inventaris_toko/data/repositories/category_repository.dart';
import 'package:inventaris_toko/data/repositories/cost_price_adjustment_repository.dart';
import 'package:inventaris_toko/data/repositories/product_repository.dart';
import 'package:inventaris_toko/data/repositories/repository_exceptions.dart';
import 'package:inventaris_toko/data/repositories/restock_list_repository.dart';
import 'package:inventaris_toko/data/repositories/stock_mutation_repository.dart';
import 'package:inventaris_toko/domain/hpp_calculator.dart';
import 'package:inventaris_toko/services/backup_service.dart';
import 'package:inventaris_toko/services/notification_service.dart';
import 'package:inventaris_toko/services/photo_storage_service.dart';
import 'package:isar_community/isar.dart';

import '../../test_support/scale_seed.dart';
import '../data/repositories/test_isar.dart';
import '../ui/screens/produk/fake_photo_storage_service.dart';

/// Backup/restore **data-integrity** tests on a realistic, multi-collection
/// dataset generated by `test_support/scale_seed.dart`.
///
/// `backup_service_test.dart` already covers the mechanics (envelope shape,
/// validation reasons, one-product round trips). What it does not answer is
/// the question a shop owner actually cares about: *after a restore, is my
/// data still the same data?* These tests answer it with two independent
/// assertions per round trip:
///
///  1. **Round-trip equality** — every field of every row in all six
///     collections, read off the models after the restore, equals what was
///     there before the wipe. Exact floats, no tolerance.
///  2. **Independent recomputation** — every restored product's
///     `currentStock` and `averageCostPrice` are checked against figures
///     replayed from the *seed plan* through [HppCalculator], and against
///     the restored ledger's own `stockAfter`. Assertion 1 alone would
///     happily pass on a database that was already wrong before the backup
///     was taken; assertion 2 is what catches pre-existing drift.
///
/// Plus the path that can actually destroy a shop's data: a restore that
/// fails partway through and has to roll back. See the
/// `rollback on failed import` group.
///
/// ## Snapshots are read off the models, never off `BackupService`
///
/// [_snapshotModels] lists every declared field of all six models by hand and
/// reads them straight from the Isar rows. Comparing two `buildBackupData()`
/// outputs instead would be worse than incomplete — it would be *blind*: a
/// field dropped from `BackupService`'s serialiser disappears from both sides
/// of the comparison at once, so real data loss reads as a pass. That was
/// verified by deleting `lastRestockQty` from `_productToJson` and watching an
/// export-vs-export comparison stay green.
///
/// The remaining gap is the one no Dart test can close without reflection: a
/// field added to a model but to neither `BackupService` nor
/// [_snapshotModels]. Adding a model field means adding it to both.
///
/// ## Scope note: `photoPath` is deliberately excluded from (1)
///
/// A real restore *cannot* preserve `photoPath`, by design: photos travel as
/// base64 inside the JSON and are written back as new files under new names
/// by `PhotoStorageService`. So the photo assertion is on **bytes**, not
/// paths — [_photoBytesByProductName] compares the decoded bytes of every
/// product's photo before and after, while [_snapshotModels] takes
/// `includePhotoPath: false` for round trips. Every other field of every
/// collection is compared with no exclusions at all.
///
/// The rollback tests pass `includePhotoPath: true`, because the rollback path
/// re-`put()`s the original paths verbatim (`useRawPhotoPath: true`) and must
/// therefore preserve them exactly.
void main() {
  // A smaller dataset than the 200/1000 the on-device scale test uses: this
  // suite seeds through the real repositories (one write transaction per
  // mutation) and runs on the host VM as part of every `flutter test`, and
  // it re-seeds per test rather than once. 40 products / 250 mutations still
  // exercises the nested category tree, uncategorised products, multi-month
  // timestamps and repeated-restock HPP averaging, which is what integrity
  // here depends on — the row count is not what makes it a real test.
  const productCount = 40;
  const mutationCount = 250;

  late Isar isar;
  late BackupService backupService;
  late FakePhotoStorageService photoStorage;
  late Directory tempDir;

  late AppSettingsRepository settingsRepository;
  late StockMutationRepository mutationRepository;
  late ProductRepository productRepository;
  late CategoryRepository categoryRepository;
  late CostPriceAdjustmentRepository costPriceAdjustmentRepository;
  late RestockListRepository restockListRepository;

  late ScaleSeedPlan plan;
  late _SeededIds seeded;

  final timings = _Timings();

  setUp(() async {
    isar = await openTestIsar();
    NotificationService.sender = _SilentNotificationSender();
    NotificationService.scheduler = _SilentWorkScheduler();
    NotificationService.alarmScheduler = _SilentAlarmScheduler();
    NotificationService.exactAlarmPermission = _PermissiveExactAlarmPermission();

    photoStorage = FakePhotoStorageService();
    backupService = BackupService(isar, photoStorageService: photoStorage);

    settingsRepository = AppSettingsRepository(isar);
    mutationRepository = StockMutationRepository(isar);
    productRepository = ProductRepository(isar, mutationRepository, settingsRepository);
    categoryRepository = CategoryRepository(isar);
    costPriceAdjustmentRepository = CostPriceAdjustmentRepository(isar);
    restockListRepository = RestockListRepository(isar);

    tempDir = await Directory.systemTemp.createTemp('backup_integrity_');

    plan = buildScaleSeedPlan(
      productCount: productCount,
      mutationCount: mutationCount,
      now: DateTime(2026, 8, 17, 10),
    );
    seeded = await timings.measure(
      'SEED $productCount products / $mutationCount mutations',
      () => _seed(
        isar: isar,
        plan: plan,
        tempDir: tempDir,
        categoryRepository: categoryRepository,
        productRepository: productRepository,
        mutationRepository: mutationRepository,
        costPriceAdjustmentRepository: costPriceAdjustmentRepository,
        restockListRepository: restockListRepository,
        settingsRepository: settingsRepository,
      ),
    );
  });

  tearDown(() async {
    await closeTestIsar(isar);
    await tempDir.delete(recursive: true);
  });

  tearDownAll(() => timings.printTable());

  /// Wipes exactly what a restore wipes, simulating the "fresh install then
  /// restore" flow rather than relying on `importBackup`'s own internal wipe.
  Future<void> wipeEverything() async {
    await isar.writeTxn(() async {
      await isar.categories.clear();
      await isar.products.clear();
      await isar.stockMutations.clear();
      await isar.appSettings.clear();
      await isar.costPriceAdjustments.clear();
      await isar.restockLists.clear();
    });
  }

  group('round trip integrity ($productCount products / $mutationCount mutations)', () {
    test('every field of every collection survives export -> wipe -> import', () async {
      final snapshotBefore = await _snapshotModels(isar, includePhotoPath: false);

      final before = await timings.measure(
        'EXPORT buildBackupData (with photos)',
        () => backupService.buildBackupData(),
      );

      // Through a real JSON string, so encoding is part of what is tested:
      // a double that does not survive `jsonEncode`/`jsonDecode` exactly
      // would show up as an inequality below, not be papered over by
      // comparing in-memory maps.
      final parsed = await timings.measure(
        'VALIDATE + parse ${jsonEncode(before).length} bytes',
        () => backupService.validateAndParse(jsonEncode(before)),
      );

      await wipeEverything();
      expect(await isar.products.count(), 0);
      expect(await isar.stockMutations.count(), 0);

      await timings.measure('IMPORT importBackup', () => backupService.importBackup(parsed));

      // Exact equality, no tolerance: this is a serialise/deserialise round
      // trip, not a computation, so every double must come back bit-identical.
      expect(await _snapshotModels(isar, includePhotoPath: false), equals(snapshotBefore));
    });

    test('collection row counts and ids are preserved exactly', () async {
      final before = await backupService.buildBackupData();
      final beforeCounts = {
        'categories': await isar.categories.count(),
        'products': await isar.products.count(),
        'mutations': await isar.stockMutations.count(),
        'costPriceAdjustments': await isar.costPriceAdjustments.count(),
        'restockLists': await isar.restockLists.count(),
      };
      final beforeProductIds = (await isar.products.where().findAll()).map((p) => p.id).toList()..sort();
      final beforeMutationIds =
          (await isar.stockMutations.where().findAll()).map((m) => m.id).toList()..sort();

      await wipeEverything();
      await backupService.importBackup(await backupService.validateAndParse(jsonEncode(before)));

      expect(await isar.categories.count(), beforeCounts['categories']);
      expect(await isar.products.count(), beforeCounts['products']);
      expect(await isar.stockMutations.count(), beforeCounts['mutations']);
      expect(await isar.costPriceAdjustments.count(), beforeCounts['costPriceAdjustments']);
      expect(await isar.restockLists.count(), beforeCounts['restockLists']);

      // Ids matter beyond tidiness: categoryId/productId cross-references are
      // raw ints with no Isar-enforced foreign key, so a shifted id set means
      // silently orphaned rows.
      expect((await isar.products.where().findAll()).map((p) => p.id).toList()..sort(),
          equals(beforeProductIds));
      expect((await isar.stockMutations.where().findAll()).map((m) => m.id).toList()..sort(),
          equals(beforeMutationIds));
    });

    test('no restored row references a missing product or category', () async {
      final before = await backupService.buildBackupData();
      await wipeEverything();
      await backupService.importBackup(await backupService.validateAndParse(jsonEncode(before)));

      final productIds = (await isar.products.where().findAll()).map((p) => p.id).toSet();
      final categoryIds = (await isar.categories.where().findAll()).map((c) => c.id).toSet();

      for (final product in await isar.products.where().findAll()) {
        final categoryId = product.categoryId;
        if (categoryId != null) {
          expect(categoryIds, contains(categoryId),
              reason: 'product ${product.id} points at missing category $categoryId');
        }
      }
      for (final category in await isar.categories.where().findAll()) {
        final parentId = category.parentId;
        if (parentId != null) {
          expect(categoryIds, contains(parentId),
              reason: 'category ${category.id} points at missing parent $parentId');
        }
      }
      for (final mutation in await isar.stockMutations.where().findAll()) {
        expect(productIds, contains(mutation.productId),
            reason: 'mutation ${mutation.id} points at missing product ${mutation.productId}');
      }
      for (final adjustment in await isar.costPriceAdjustments.where().findAll()) {
        expect(productIds, contains(adjustment.productId));
      }
      for (final list in await isar.restockLists.where().findAll()) {
        for (final item in list.items) {
          expect(productIds, contains(item.productId));
        }
      }
    });

    test('restored stock and HPP match figures recomputed from the seed plan', () async {
      final expectedStock = <int, double>{};
      final expectedHpp = <int, double?>{};
      _replayPlan(plan, expectedStock, expectedHpp);

      final before = await backupService.buildBackupData();
      await wipeEverything();
      await backupService.importBackup(await backupService.validateAndParse(jsonEncode(before)));

      for (final seedProduct in plan.products) {
        final id = seeded.productIdByIndex[seedProduct.index]!;
        final restored = await isar.products.get(id);
        expect(restored, isNotNull, reason: 'product index ${seedProduct.index} missing after restore');

        // Exact equality on purpose. The replay below performs the same
        // arithmetic in the same order as the repository (both go through
        // HppCalculator, mutation by mutation, in recording order), so any
        // difference at all is a real divergence — not float noise.
        expect(restored!.currentStock, expectedStock[seedProduct.index],
            reason: 'currentStock drifted for ${seedProduct.name} (id $id)');
        // A manual HPP correction, if the seed applied one to this product,
        // supersedes whatever the ledger replay produced — that is what
        // "Harga modal (koreksi)" does.
        final expectedCost = seeded.hppOverrideByProductIndex.containsKey(seedProduct.index)
            ? seeded.hppOverrideByProductIndex[seedProduct.index]
            : expectedHpp[seedProduct.index];
        expect(restored.averageCostPrice, expectedCost,
            reason: 'averageCostPrice drifted for ${seedProduct.name} (id $id)');
      }
    });

    test('restored stock agrees with the restored ledger it came from', () async {
      final before = await backupService.buildBackupData();
      await wipeEverything();
      await backupService.importBackup(await backupService.validateAndParse(jsonEncode(before)));

      final mutationsByProduct = <int, List<StockMutation>>{};
      for (final mutation in await isar.stockMutations.where().findAll()) {
        mutationsByProduct.putIfAbsent(mutation.productId, () => []).add(mutation);
      }

      for (final product in await isar.products.where().findAll()) {
        final rows = mutationsByProduct[product.id];
        if (rows == null || rows.isEmpty) continue;
        // Ordered by id, not createdAt: seeded timestamps are drawn at
        // minute granularity and can tie, whereas id is strictly the order
        // the repository recorded (and therefore computed stock) in.
        rows.sort((a, b) => a.id.compareTo(b.id));

        var replayed = 0.0;
        for (final row in rows) {
          replayed += row.type == StockMutationType.stockIn ? row.quantity : -row.quantity;
        }

        expect(product.currentStock, replayed,
            reason: 'product ${product.id} stock disagrees with the sum of its restored mutations');
        expect(product.currentStock, rows.last.stockAfter,
            reason: 'product ${product.id} stock disagrees with its last mutation stockAfter');
      }
    });

    test('photo bytes survive the round trip (paths intentionally do not)', () async {
      final photosBefore = await _photoBytesByProductName(isar);
      expect(photosBefore, isNotEmpty, reason: 'seed must include products with photos');

      final before = await backupService.buildBackupData();
      await wipeEverything();
      photoStorage.writtenBytes.clear();

      await backupService.importBackup(await backupService.validateAndParse(jsonEncode(before)));

      // Every photo was handed back to PhotoStorageService for rewriting,
      // exactly once each.
      expect(photoStorage.writtenBytes, hasLength(photosBefore.length));

      // And each product still owns a photo whose *content* is its own. The
      // fake storage returns a new path per write, so the path necessarily
      // differs — the bytes must not.
      final photosAfter = <String, List<int>>{};
      final written = {
        for (var i = 0; i < photoStorage.writtenBytes.length; i++)
          '/fake/photos/restored_${i + 1}.jpg': photoStorage.writtenBytes[i],
      };
      for (final product in await isar.products.where().findAll()) {
        final path = product.photoPath;
        if (path == null) continue;
        expect(written.containsKey(path), isTrue,
            reason: 'restored photoPath $path was not produced by PhotoStorageService');
        photosAfter[product.name] = written[path]!;
      }

      expect(photosAfter.keys.toSet(), equals(photosBefore.keys.toSet()),
          reason: 'the set of products owning a photo changed across the restore');
      for (final name in photosBefore.keys) {
        expect(photosAfter[name], equals(photosBefore[name]),
            reason: 'photo bytes changed for $name');
      }
    });

    test('appSettings restores as a single row at the singleton id', () async {
      final beforeSettings = await settingsRepository.get();
      final before = await backupService.buildBackupData();
      await wipeEverything();
      await backupService.importBackup(await backupService.validateAndParse(jsonEncode(before)));

      final rows = await isar.appSettings.where().findAll();
      expect(rows, hasLength(1), reason: 'restore must not duplicate the settings singleton');
      // AppSettingsRepository reads settings by a hardcoded id of 0; a
      // restored row landing anywhere else would be invisible to the whole
      // app, which would then silently fall back to defaults.
      expect(rows.single.id, 0);
      expect(rows.single.restockLeadTimeDays, beforeSettings.restockLeadTimeDays);
      expect(rows.single.restockCoverDays, beforeSettings.restockCoverDays);
      expect(rows.single.dailySummaryHour, beforeSettings.dailySummaryHour);
      expect(rows.single.criticalStockAlertHour3, beforeSettings.criticalStockAlertHour3);
      expect(rows.single.defaultMinStockThreshold, beforeSettings.defaultMinStockThreshold);
    });

    test('a stray non-singleton appSettings row is dropped, not relocated', () async {
      // Nothing in the app can produce this — AppSettingsRepository always
      // writes id 0 — so this pins the behaviour rather than reporting a bug:
      // buildBackupData exports `AppSettingsRepository.get()`, i.e. the id-0
      // row only, so a hand-written row at another id is not carried across a
      // restore and does not overwrite the real settings either.
      final stray = AppSettings()
        ..id = 7
        ..defaultMinStockThreshold = 99
        ..dailySummaryEnabled = false
        ..dailySummaryHour = 1
        ..dailySummaryMinute = 1
        ..criticalStockAlertEnabled = false
        ..criticalStockAlertHour1 = 1
        ..criticalStockAlertMinute1 = 1
        ..restockLeadTimeDays = 1
        ..restockCoverDays = 1
        ..batteryOptimizationDialogDismissed = false;
      await isar.writeTxn(() => isar.appSettings.put(stray));

      final realSettings = await settingsRepository.get();
      final before = await backupService.buildBackupData();
      await wipeEverything();
      await backupService.importBackup(await backupService.validateAndParse(jsonEncode(before)));

      final rows = await isar.appSettings.where().findAll();
      expect(rows, hasLength(1));
      expect(rows.single.id, 0);
      expect(rows.single.defaultMinStockThreshold, realSettings.defaultMinStockThreshold);
      expect(await isar.appSettings.get(7), isNull);
    });

    test('via a real backup file on disk, lastBackupAt is the only difference', () async {
      final file = await backupService.exportToFile(
        directory: tempDir,
        now: DateTime(2026, 8, 17, 12, 30, 15),
      );
      // exportToFile stamps lastBackupAt *after* building the payload, so the
      // file necessarily carries the pre-export value. That is the one field
      // a file round trip legitimately rewinds; everything else must match.
      final snapshotBefore = await _snapshotModels(isar, includePhotoPath: false);
      expect((await settingsRepository.get()).lastBackupAt, DateTime(2026, 8, 17, 12, 30, 15));

      final parsed = await backupService.validateAndParse(await file.readAsString());
      await wipeEverything();
      await backupService.importBackup(parsed);

      final snapshotAfter = await _snapshotModels(isar, includePhotoPath: false);

      expect(snapshotAfter['appSettings']!.single['lastBackupAt'], isNull,
          reason: 'the file was written before lastBackupAt was stamped');
      snapshotAfter['appSettings']!.single.remove('lastBackupAt');
      snapshotBefore['appSettings']!.single.remove('lastBackupAt');
      expect(snapshotAfter, equals(snapshotBefore));
    });
  });

  group('version rejection', () {
    test('a future schema version is rejected outright — there is no migration path', () async {
      final backup = await backupService.buildBackupData();
      backup['version'] = backupSchemaVersion + 1;

      await expectLater(
        backupService.validateAndParse(jsonEncode(backup)),
        throwsA(isA<BackupValidationException>()
            .having((e) => e.reason, 'reason', BackupValidationFailureReason.unsupportedVersion)
            .having((e) => e.foundVersion, 'foundVersion', backupSchemaVersion + 1)),
      );

      // Rejection happens before anything is touched.
      expect(await isar.products.count(), plan.products.length);
    });
  });

  group('rollback on failed import', () {
    /// Every field of every row, with no exclusions at all — including
    /// `photoPath`, which rollback re-`put()`s verbatim (`useRawPhotoPath:
    /// true`) and must therefore preserve exactly.
    Future<Map<String, List<Map<String, Object?>>>> fullSnapshot() =>
        _snapshotModels(isar, includePhotoPath: true);

    /// Asserts nothing at all changed, and that the ledger still explains
    /// the stock — a rollback that restores rows but leaves them mutually
    /// inconsistent is still corruption.
    Future<void> expectFullyRestored(
      Map<String, List<Map<String, Object?>>> expectedSnapshot,
    ) async {
      expect(await fullSnapshot(), equals(expectedSnapshot));

      for (final product in await isar.products.where().findAll()) {
        final rows = await isar.stockMutations.filter().productIdEqualTo(product.id).findAll();
        if (rows.isEmpty) continue;
        rows.sort((a, b) => a.id.compareTo(b.id));
        expect(product.currentStock, rows.last.stockAfter,
            reason: 'after rollback, product ${product.id} disagrees with its ledger');
      }
    }

    test('failure while writing mutations rolls back to the exact pre-import state', () async {
      final snapshot = await fullSnapshot();

      // A malformed record partway through the mutations stream. Products and
      // categories are already committed by the time it throws, so rollback
      // has to undo a genuinely half-imported database rather than a no-op.
      final corrupt = await backupService.buildBackupData();
      final mutations = (corrupt['data'] as Map)['mutations'] as List;
      expect(mutations.length, greaterThan(20));
      (mutations[mutations.length ~/ 2] as Map)['type'] = 'not_a_mutation_type';

      await expectLater(
        backupService.importBackup(corrupt),
        throwsA(isA<BackupRestoreException>()
            .having((e) => e.rollbackSucceeded, 'rollbackSucceeded', isTrue)),
      );

      await expectFullyRestored(snapshot);
    });

    test('failure while writing products rolls back to the exact pre-import state', () async {
      final snapshot = await fullSnapshot();

      // Fails during photo decode/write, i.e. before any product row is put
      // but after the categories transaction has committed.
      final failingService = BackupService(isar, photoStorageService: _ThrowingPhotoStorageService());
      final backup = await backupService.buildBackupData();

      await expectLater(
        failingService.importBackup(backup),
        throwsA(isA<BackupRestoreException>()
            .having((e) => e.rollbackSucceeded, 'rollbackSucceeded', isTrue)),
      );

      await expectFullyRestored(snapshot);
    });

    test('failure while writing app settings rolls back to the exact pre-import state', () async {
      final snapshot = await fullSnapshot();

      // The last collection imported: everything else is committed, so this
      // is the deepest half-import the service can produce.
      final corrupt = await backupService.buildBackupData();
      ((corrupt['data'] as Map)['appSettings'] as Map)['restockLeadTimeDays'] = 'not_an_int';

      await expectLater(
        backupService.importBackup(corrupt),
        throwsA(isA<BackupRestoreException>()
            .having((e) => e.rollbackSucceeded, 'rollbackSucceeded', isTrue)),
      );

      await expectFullyRestored(snapshot);
    });

    test('rolled-back photo paths are the original files, not rewritten copies', () async {
      final pathsBefore = {
        for (final product in await isar.products.where().findAll())
          if (product.photoPath != null) product.name: product.photoPath!,
      };
      expect(pathsBefore, isNotEmpty);
      photoStorage.writtenBytes.clear();

      final corrupt = await backupService.buildBackupData();
      ((corrupt['data'] as Map)['appSettings'] as Map)['restockLeadTimeDays'] = 'not_an_int';

      await expectLater(backupService.importBackup(corrupt), throwsA(isA<BackupRestoreException>()));

      final pathsAfter = {
        for (final product in await isar.products.where().findAll())
          if (product.photoPath != null) product.name: product.photoPath!,
      };
      expect(pathsAfter, equals(pathsBefore));
      for (final path in pathsAfter.values) {
        expect(await File(path).exists(), isTrue,
            reason: 'rollback must point at the original photo file, which is never deleted');
      }
    });
  });
}

/// Ids assigned while seeding, so plan-relative expectations can be checked
/// against real rows.
class _SeededIds {
  _SeededIds(this.productIdByIndex, this.categoryIdByIndex, this.hppOverrideByProductIndex);

  final Map<int, int> productIdByIndex;
  final Map<int, int> categoryIdByIndex;

  /// Manual "Harga modal (koreksi)" overrides applied after the ledger was
  /// recorded. [CostPriceAdjustmentRepository.recordAdjustment] overwrites
  /// `Product.averageCostPrice` outright, so a plan replay alone does not
  /// predict the final HPP for these products — the override wins. Value may
  /// be null, which is a deliberate "clear HPP back to no data".
  final Map<int, double?> hppOverrideByProductIndex;
}

/// Writes [plan] through the real repositories — so the seeded state is
/// exactly what the app itself would produce (stock, weighted-average HPP,
/// price snapshots, critical-alert state) — then backdates every mutation to
/// its planned timestamp, which is the one thing
/// [StockMutationRepository.recordMutation] will not accept.
///
/// On top of the plan it adds the things a plan of pure stock movements
/// cannot express but a real backup must carry: photos on disk, an archived
/// product, cost-price adjustments, restock lists (open and completed), and
/// non-default app settings.
Future<_SeededIds> _seed({
  required Isar isar,
  required ScaleSeedPlan plan,
  required Directory tempDir,
  required CategoryRepository categoryRepository,
  required ProductRepository productRepository,
  required StockMutationRepository mutationRepository,
  required CostPriceAdjustmentRepository costPriceAdjustmentRepository,
  required RestockListRepository restockListRepository,
  required AppSettingsRepository settingsRepository,
}) async {
  final categoryIdByIndex = <int, int>{};
  for (final category in plan.categories) {
    final parentIndex = category.parentIndex;
    final created = await categoryRepository.create(
      category.name,
      parentId: parentIndex == null ? null : categoryIdByIndex[parentIndex],
    );
    categoryIdByIndex[category.index] = created.id;
  }

  final productIdByIndex = <int, int>{};
  for (final product in plan.products) {
    final categoryIndex = product.categoryIndex;
    final created = await productRepository.create(
      name: product.name,
      categoryId: categoryIndex == null ? null : categoryIdByIndex[categoryIndex],
      sellPrice: product.sellPrice,
      unit: product.unit,
      minStockThreshold: product.minStockThreshold,
      // Every fifth product carries pack/dus factors and fractional
      // quantities, so those nullable fields are not all null in the backup.
      unitsPerPack: product.index % 5 == 0 ? 12 : null,
      unitsPerDus: product.index % 5 == 0 ? 144 : null,
      allowsFractionalQuantity: product.index % 5 == 0,
      code: product.index % 3 == 0 ? 'SKU-${product.index.toString().padLeft(4, '0')}' : null,
    );
    productIdByIndex[product.index] = created.id;
  }

  final mutationIds = <int>[];
  for (final mutation in plan.mutations) {
    final recorded = await mutationRepository.recordMutation(
      productId: productIdByIndex[mutation.productIndex]!,
      type: mutation.type == SeedMutationType.stockIn
          ? StockMutationType.stockIn
          : StockMutationType.stockOut,
      quantity: mutation.quantity,
      costPricePerUnit: mutation.costPricePerUnit,
      note: mutation.type == SeedMutationType.stockIn ? 'kulakan' : null,
    );
    mutationIds.add(recorded.id);
  }

  final rows = await isar.stockMutations.getAll(mutationIds);
  await isar.writeTxn(() async {
    for (var i = 0; i < plan.mutations.length; i++) {
      final row = rows[i]!;
      row.createdAt = plan.mutations[i].at;
      await isar.stockMutations.put(row);
    }
  });

  // Photos: real files on disk, distinct bytes per product so a mix-up
  // during restore cannot pass as a match.
  for (var i = 0; i < 4; i++) {
    final id = productIdByIndex[i]!;
    final file = File('${tempDir.path}/photo_$i.jpg');
    await file.writeAsBytes(List<int>.generate(16, (b) => (i + 1) * 10 + b));
    await isar.writeTxn(() async {
      final product = (await isar.products.get(id))!;
      product.photoPath = file.path;
      await isar.products.put(product);
    });
  }

  // An archived product, so isArchived/archivedAt are exercised.
  await isar.writeTxn(() async {
    final product = (await isar.products.get(productIdByIndex[1]!))!;
    product.isArchived = true;
    product.archivedAt = DateTime(2026, 6, 1, 9, 15);
    product.lastRestockQty = 24;
    await isar.products.put(product);
  });

  final hppOverrideByProductIndex = <int, double?>{};
  for (var i = 0; i < 6; i++) {
    // i == 1 clears HPP instead of setting it, so the nullable branch of
    // both the adjustment row and Product.averageCostPrice is in the backup.
    final newCost = i == 1 ? null : 1500 + i * 250.0;
    await costPriceAdjustmentRepository.recordAdjustment(
      productId: productIdByIndex[i * 3]!,
      newCost: newCost,
      note: i.isEven ? 'koreksi manual $i' : null,
    );
    hppOverrideByProductIndex[i * 3] = newCost;
  }

  for (var i = 0; i < 3; i++) {
    final list = await restockListRepository.create(
      supplierName: i == 0 ? null : 'Grosir $i',
      items: [
        for (var j = 0; j < 4; j++)
          RestockListItemInput(
            productId: productIdByIndex[i * 4 + j]!,
            productName: plan.products[i * 4 + j].name,
            qtyInPcs: (j + 1) * 6,
            inputUnitWasPack: j.isEven,
          ),
      ],
    );
    if (i == 2) {
      await isar.writeTxn(() async {
        final stored = (await isar.restockLists.get(list.id))!;
        stored.completedAt = DateTime(2026, 8, 1, 14, 20);
        stored.items = stored.items.map((item) => item..isChecked = true).toList();
        await isar.restockLists.put(stored);
      });
    }
  }

  // Non-default settings across every field the backup carries, including
  // the nullable slot-2/slot-3 alert times.
  await settingsRepository.updateDefaultMinStockThreshold(6);
  await settingsRepository.updateDailySummaryEnabled(true);
  await settingsRepository.updateDailySummaryTime(hour: 20, minute: 45);
  await settingsRepository.updateCriticalStockAlertEnabled(true);
  await settingsRepository.updateCriticalStockAlertSlots([
    (hour: 7, minute: 5),
    (hour: 13, minute: 35),
    (hour: 19, minute: 55),
  ]);
  await settingsRepository.updateRestockLeadTimeDays(5);
  await settingsRepository.updateRestockCoverDays(11);
  await settingsRepository.dismissBatteryOptimizationDialog();

  return _SeededIds(productIdByIndex, categoryIdByIndex, hppOverrideByProductIndex);
}

/// Replays [plan] into per-product final stock and HPP, using the app's own
/// [HppCalculator] and the same per-mutation order the repository used.
///
/// Independent of both `BackupService` and `StockMutationRepository`: the
/// inputs are the plan's own quantities and cost prices, never anything read
/// back out of the database. That is what makes it able to catch stock/HPP
/// that was already wrong *before* the backup was taken.
void _replayPlan(
  ScaleSeedPlan plan,
  Map<int, double> stock,
  Map<int, double?> hpp,
) {
  for (final product in plan.products) {
    stock[product.index] = 0;
    hpp[product.index] = null;
  }
  for (final mutation in plan.mutations) {
    final index = mutation.productIndex;
    final current = stock[index]!;
    switch (mutation.type) {
      case SeedMutationType.stockIn:
        final incoming = mutation.costPricePerUnit;
        if (incoming != null) {
          hpp[index] = HppCalculator.calculateNewAverage(
            currentStock: current,
            currentAvgCost: hpp[index] ?? 0,
            incomingQty: mutation.quantity,
            incomingCostPrice: incoming,
          );
        }
        stock[index] = current + mutation.quantity;
      case SeedMutationType.stockOut:
        stock[index] = current - mutation.quantity;
    }
  }
}

/// Product name -> decoded photo bytes, read straight from the files on
/// disk. Keyed by name because ids survive a restore but paths do not, and
/// names are unique in the seeded dataset.
Future<Map<String, List<int>>> _photoBytesByProductName(Isar isar) async {
  final result = <String, List<int>>{};
  for (final product in await isar.products.where().findAll()) {
    final path = product.photoPath;
    if (path == null) continue;
    result[product.name] = await File(path).readAsBytes();
  }
  return result;
}

/// Every field of every row in all six collections, read directly off the
/// model objects and ordered by id, as a plain comparable structure.
///
/// Deliberately *not* built from `buildBackupData()` — see this file's header
/// for why an export-vs-export comparison cannot detect a field the serialiser
/// has stopped carrying.
///
/// [includePhotoPath] is false for restore round trips (paths legitimately
/// change; bytes are asserted separately) and true for rollback, which must
/// preserve paths verbatim.
Future<Map<String, List<Map<String, Object?>>>> _snapshotModels(
  Isar isar, {
  required bool includePhotoPath,
}) async {
  final categories = await isar.categories.where().findAll();
  final products = await isar.products.where().findAll();
  final mutations = await isar.stockMutations.where().findAll();
  final adjustments = await isar.costPriceAdjustments.where().findAll();
  final restockLists = await isar.restockLists.where().findAll();
  final settings = await isar.appSettings.where().findAll();

  categories.sort((a, b) => a.id.compareTo(b.id));
  products.sort((a, b) => a.id.compareTo(b.id));
  mutations.sort((a, b) => a.id.compareTo(b.id));
  adjustments.sort((a, b) => a.id.compareTo(b.id));
  restockLists.sort((a, b) => a.id.compareTo(b.id));
  settings.sort((a, b) => a.id.compareTo(b.id));

  return {
    'categories': [
      for (final c in categories)
        {'id': c.id, 'name': c.name, 'parentId': c.parentId, 'createdAt': c.createdAt},
    ],
    'products': [
      for (final p in products)
        {
          'id': p.id,
          'name': p.name,
          'code': p.code,
          'categoryId': p.categoryId,
          if (includePhotoPath) 'photoPath': p.photoPath,
          // Whether a product *has* a photo at all is asserted on every
          // round trip; only the path itself is conditional.
          'hasPhoto': p.photoPath != null,
          'sellPrice': p.sellPrice,
          'unit': p.unit,
          'currentStock': p.currentStock,
          'minStockThreshold': p.minStockThreshold,
          'averageCostPrice': p.averageCostPrice,
          'createdAt': p.createdAt,
          'updatedAt': p.updatedAt,
          'isArchived': p.isArchived,
          'archivedAt': p.archivedAt,
          'criticalStockAlertState': p.criticalStockAlertState,
          'unitsPerPack': p.unitsPerPack,
          'lastRestockQty': p.lastRestockQty,
          'unitsPerDus': p.unitsPerDus,
          'allowsFractionalQuantity': p.allowsFractionalQuantity,
        },
    ],
    'mutations': [
      for (final m in mutations)
        {
          'id': m.id,
          'productId': m.productId,
          'type': m.type,
          'quantity': m.quantity,
          'note': m.note,
          'stockAfter': m.stockAfter,
          'createdAt': m.createdAt,
          'enteredUnit': m.enteredUnit,
          'enteredQuantity': m.enteredQuantity,
          'sellPriceSnapshot': m.sellPriceSnapshot,
          'costPriceSnapshot': m.costPriceSnapshot,
          'snapshotBackfilled': m.snapshotBackfilled,
        },
    ],
    'costPriceAdjustments': [
      for (final a in adjustments)
        {
          'id': a.id,
          'productId': a.productId,
          'oldCost': a.oldCost,
          'newCost': a.newCost,
          'adjustedAt': a.adjustedAt,
          'note': a.note,
        },
    ],
    'restockLists': [
      for (final l in restockLists)
        {
          'id': l.id,
          'supplierName': l.supplierName,
          'createdAt': l.createdAt,
          'completedAt': l.completedAt,
          'items': [
            for (final item in l.items)
              {
                'productId': item.productId,
                'productNameSnapshot': item.productNameSnapshot,
                'qtyInPcs': item.qtyInPcs,
                'inputUnitWasPack': item.inputUnitWasPack,
                'isChecked': item.isChecked,
              },
          ],
        },
    ],
    'appSettings': [
      for (final s in settings)
        {
          'id': s.id,
          'defaultMinStockThreshold': s.defaultMinStockThreshold,
          'lastBackupAt': s.lastBackupAt,
          'dailySummaryEnabled': s.dailySummaryEnabled,
          'dailySummaryHour': s.dailySummaryHour,
          'dailySummaryMinute': s.dailySummaryMinute,
          'criticalStockAlertEnabled': s.criticalStockAlertEnabled,
          'criticalStockAlertHour1': s.criticalStockAlertHour1,
          'criticalStockAlertMinute1': s.criticalStockAlertMinute1,
          'criticalStockAlertHour2': s.criticalStockAlertHour2,
          'criticalStockAlertMinute2': s.criticalStockAlertMinute2,
          'criticalStockAlertHour3': s.criticalStockAlertHour3,
          'criticalStockAlertMinute3': s.criticalStockAlertMinute3,
          'restockLeadTimeDays': s.restockLeadTimeDays,
          'restockCoverDays': s.restockCoverDays,
          'batteryOptimizationDialogDismissed': s.batteryOptimizationDialogDismissed,
        },
    ],
  };
}

class _ThrowingPhotoStorageService implements PhotoStorageService {
  @override
  Future<String?> pickAndSavePhoto(PhotoPickSource source) async => null;

  @override
  Future<void> deletePhoto(String path) async {}

  @override
  Future<String> writePhotoBytes(List<int> bytes, {required String extension}) async {
    throw const FileSystemException('simulated disk failure while restoring a photo');
  }
}

class _SilentNotificationSender implements NotificationSender {
  @override
  Future<void> showNotification({
    required int id,
    required String title,
    required String body,
    required String channelId,
    required String channelName,
    required String channelDescription,
    required bool highImportance,
    String? payload,
  }) async {}

  @override
  Future<void> cancelAllNotifications() async {}
}

class _SilentWorkScheduler implements WorkScheduler {
  @override
  Future<void> cancel(String uniqueName) async {}

  @override
  Future<void> registerOneOff(String uniqueName, String taskName, {required Duration initialDelay}) async {}

  @override
  Future<void> registerPeriodic(String uniqueName, String taskName, {required Duration frequency}) async {}
}

class _SilentAlarmScheduler implements AlarmScheduler {
  @override
  Future<void> scheduleExact(int slotIndex, DateTime time) async {}

  @override
  Future<void> cancel(int slotIndex) async {}
}

class _PermissiveExactAlarmPermission implements ExactAlarmPermission {
  @override
  Future<bool> canScheduleExactAlarms() async => true;

  @override
  Future<void> requestExactAlarmsPermission() async {}
}

/// Report-only wall-clock timings, printed once at the end of the run. These
/// are never asserted on — a shared CI machine's timing is not a contract —
/// they exist so a restore that becomes pathologically slow is at least
/// visible in the test output.
class _Timings {
  final Map<String, List<int>> _millisByLabel = {};

  Future<T> measure<T>(String label, Future<T> Function() body) async {
    final stopwatch = Stopwatch()..start();
    final result = await body();
    stopwatch.stop();
    _millisByLabel.putIfAbsent(label, () => []).add(stopwatch.elapsedMilliseconds);
    return result;
  }

  void printTable() {
    if (_millisByLabel.isEmpty) return;
    final width = _millisByLabel.keys.map((k) => k.length).reduce((a, b) => a > b ? a : b);
    // ignore: avoid_print
    print('\n${'Backup/restore integrity timings (report only)'.padRight(width)}   n     avg ms');
    for (final entry in _millisByLabel.entries) {
      final avg = entry.value.reduce((a, b) => a + b) / entry.value.length;
      // ignore: avoid_print
      print('${entry.key.padRight(width)}   ${entry.value.length.toString().padLeft(3)}   '
          '${avg.toStringAsFixed(1).padLeft(8)}');
    }
  }
}
