/// Deterministic synthetic-dataset generation for the 1000-mutation scale
/// test (`integration_test/scale_performance_test.dart`) and the safety
/// guard that keeps it off the production database.
///
/// Deliberately pure Dart — no Flutter, no Isar, no models — for two
/// reasons: the plan is generated *before* anything is written, so it can
/// be reasoned about (and unit-tested under `flutter test`) on its own;
/// and [expectedProfitFor] can then compute the profit the seeded data
/// *should* produce independently of the app's own query path, giving the
/// scale test a real cross-check rather than a tautology.
///
/// The expected-profit simulation mirrors the app's rules exactly:
/// weighted-average HPP per stock-in (`HppCalculator.calculateNewAverage`)
/// and per-mutation price snapshots resolved the way `MutationPricing`
/// resolves them. If those rules change, this must change with them — the
/// unit tests in `test/support/scale_seed_test.dart` pin the arithmetic.
library;

import 'dart:math';

/// Mirrors `StockMutationType` without importing it, keeping this library
/// free of any Isar/model dependency. Mapped at the seeding call site.
enum SeedMutationType { stockIn, stockOut }

/// A category to create, identified by [index] with an optional
/// [parentIndex] into the same list. Parents always appear before their
/// children so a single forward pass can create them all.
class SeedCategory {
  const SeedCategory({
    required this.index,
    required this.name,
    this.parentIndex,
  });

  final int index;
  final String name;
  final int? parentIndex;

  bool get isRoot => parentIndex == null;
}

/// A product to create. Always created with zero initial stock and no
/// cost data: every unit of stock and every rupiah of HPP arrives through
/// an explicit [SeedMutation] instead, so the ledger is the single source
/// of truth for the seeded state — the same invariant the app enforces.
class SeedProduct {
  const SeedProduct({
    required this.index,
    required this.name,
    required this.categoryIndex,
    required this.sellPrice,
    required this.unit,
    required this.minStockThreshold,
  });

  final int index;
  final String name;

  /// Index into [ScaleSeedPlan.categories], or `null` for an
  /// uncategorised product (the "Lainnya" bucket).
  final int? categoryIndex;

  final double sellPrice;
  final String unit;
  final double minStockThreshold;
}

/// One mutation to record, against `products[productIndex]`.
///
/// [at] is the timestamp the row should end up carrying. It cannot be
/// passed to `StockMutationRepository.recordMutation` (which always stamps
/// `DateTime.now()`), so the seeder rewrites `createdAt` afterwards; the
/// list is generated in ascending [at] order so recording it front-to-back
/// keeps stock arithmetic and timestamps in the same order.
class SeedMutation {
  const SeedMutation({
    required this.productIndex,
    required this.type,
    required this.quantity,
    required this.at,
    this.costPricePerUnit,
  });

  final int productIndex;
  final SeedMutationType type;
  final double quantity;
  final DateTime at;

  /// Only meaningful for [SeedMutationType.stockIn]; `null` on every
  /// stock-out, matching the repository's own contract.
  final double? costPricePerUnit;
}

/// A complete, deterministic dataset description: what to create and in
/// what order. Generated by [buildScaleSeedPlan].
class ScaleSeedPlan {
  const ScaleSeedPlan({
    required this.categories,
    required this.products,
    required this.mutations,
  });

  final List<SeedCategory> categories;
  final List<SeedProduct> products;

  /// Ascending by [SeedMutation.at]. Guaranteed never to drive a
  /// product's stock negative — this is a positive-path dataset, so the
  /// repository must accept every row without rejecting any.
  final List<SeedMutation> mutations;
}

/// The profit figures the seeded data must produce, as computed from the
/// plan alone.
class ExpectedProfit {
  const ExpectedProfit({
    required this.totalRevenue,
    required this.totalCost,
    required this.quantitySold,
    required this.productsSold,
    required this.finalStockByProductIndex,
  });

  final double totalRevenue;
  final double totalCost;
  final double quantitySold;

  /// Distinct products with at least one stock-out — what
  /// `ProfitReport.productsSold` reports.
  final int productsSold;

  /// Stock each product ends on, for cross-checking low-stock detection.
  final Map<int, double> finalStockByProductIndex;

  double get totalProfit => totalRevenue - totalCost;
}

/// Realistic Indonesian *kulakan* category tree: 6 roots, each with 2–3
/// children, so products spread across a nested structure rather than a
/// flat list — matching how the app's own category picker is used.
const _categoryTree = <String, List<String>>{
  'Makanan Ringan': ['Keripik', 'Biskuit', 'Permen'],
  'Minuman': ['Air Mineral', 'Teh & Kopi', 'Sirup'],
  'Sembako': ['Beras', 'Minyak Goreng', 'Gula & Tepung'],
  'Kebutuhan Rumah': ['Sabun & Deterjen', 'Alat Kebersihan'],
  'Perawatan Diri': ['Sampo', 'Pasta Gigi'],
  'Alat Tulis': ['Pulpen & Pensil', 'Buku Tulis'],
};

const _units = ['pcs', 'bungkus', 'botol', 'sachet', 'dus'];

/// Builds the dataset description. Fully deterministic for a given
/// [randomSeed], so a re-run measures the same data and a surprising
/// number can be reproduced rather than chased.
///
/// [uncategorisedEvery] leaves every Nth product without a category, so
/// the "Lainnya" bucket is exercised too. [criticalEvery] steers every Nth
/// product's mutations towards ending at or below its threshold, giving
/// the notification-accuracy check a known-size expected set instead of
/// whatever the random walk happens to produce.
///
/// [monthsBack] spreads timestamps back from [now] across that many
/// months. Throws [ArgumentError] on a plan that couldn't be satisfied
/// (fewer mutations than products, which would leave a product with no
/// opening stock-in).
ScaleSeedPlan buildScaleSeedPlan({
  int productCount = 200,
  int mutationCount = 1000,
  int randomSeed = 20260817,
  int monthsBack = 6,
  int uncategorisedEvery = 17,
  int criticalEvery = 11,
  DateTime? now,
}) {
  if (productCount <= 0) {
    throw ArgumentError.value(productCount, 'productCount', 'must be > 0');
  }
  if (mutationCount < productCount) {
    throw ArgumentError.value(
      mutationCount,
      'mutationCount',
      'must be >= productCount so every product gets an opening stock-in',
    );
  }
  if (monthsBack <= 0) {
    throw ArgumentError.value(monthsBack, 'monthsBack', 'must be > 0');
  }

  final random = Random(randomSeed);
  final effectiveNow = now ?? DateTime.now();

  final categories = _buildCategories();
  final leafIndexes = [
    for (final category in categories)
      if (!category.isRoot) category.index,
  ];

  final products = <SeedProduct>[
    for (var i = 0; i < productCount; i++)
      SeedProduct(
        index: i,
        name: 'Produk Uji ${(i + 1).toString().padLeft(3, '0')}',
        categoryIndex: (i + 1) % uncategorisedEvery == 0
            ? null
            : leafIndexes[i % leafIndexes.length],
        // 1_000–50_500, rounded to the nearest 500 so figures read like
        // real prices rather than noise.
        sellPrice: (1000 + random.nextInt(100) * 500).toDouble(),
        unit: _units[i % _units.length],
        minStockThreshold: (3 + random.nextInt(8)).toDouble(),
      ),
  ];

  // Timestamps are drawn first and sorted, then assigned to the generated
  // mutations in order. Doing it this way (rather than picking a time per
  // mutation) is what guarantees the ascending-order invariant the seeder
  // relies on to backdate rows without reordering the stock arithmetic.
  final windowStart = DateTime(
    effectiveNow.year,
    effectiveNow.month - monthsBack,
    effectiveNow.day,
  );
  final windowMinutes =
      effectiveNow.difference(windowStart).inMinutes;
  final timestamps = <DateTime>[
    for (var i = 0; i < mutationCount; i++)
      windowStart.add(Duration(minutes: random.nextInt(windowMinutes))),
  ]..sort();

  // The forward simulation below is what keeps this a positive-path
  // dataset: stock is tracked as the plan is built, so a stock-out is
  // only ever emitted for a quantity the product actually has.
  final stock = <int, double>{for (final p in products) p.index: 0};
  final openedProducts = <int>{};

  final mutations = <SeedMutation>[];
  for (var i = 0; i < mutationCount; i++) {
    final at = timestamps[i];

    // The first `productCount` mutations open each product with a
    // stock-in, so no product is ever sold before it has stock or a cost
    // price. The rest are a mixed random walk.
    if (i < productCount) {
      final product = products[i];
      final quantity = (20 + random.nextInt(60)).toDouble();
      stock[product.index] = stock[product.index]! + quantity;
      openedProducts.add(product.index);
      mutations.add(
        SeedMutation(
          productIndex: product.index,
          type: SeedMutationType.stockIn,
          quantity: quantity,
          at: at,
          costPricePerUnit: _costPriceFor(product, random),
        ),
      );
      continue;
    }

    final product = products[random.nextInt(products.length)];
    final available = stock[product.index]!;
    final wantsCritical = (product.index + 1) % criticalEvery == 0;

    // Restock when there is nothing to sell; otherwise sell. Products
    // steered towards critical are never restocked back up, so they
    // reliably end at or below threshold.
    final restocking = available <= 0 ||
        (!wantsCritical && available <= product.minStockThreshold) ||
        (!wantsCritical && random.nextInt(100) < 35);

    if (restocking) {
      final quantity = (10 + random.nextInt(40)).toDouble();
      stock[product.index] = available + quantity;
      mutations.add(
        SeedMutation(
          productIndex: product.index,
          type: SeedMutationType.stockIn,
          quantity: quantity,
          at: at,
          costPricePerUnit: _costPriceFor(product, random),
        ),
      );
    } else {
      // Never more than what's on hand — the repository would reject it,
      // and this task's dataset is deliberately positive-path only.
      final quantity =
          (1 + random.nextInt(max(1, min(12, available.toInt())))).toDouble();
      stock[product.index] = available - quantity;
      mutations.add(
        SeedMutation(
          productIndex: product.index,
          type: SeedMutationType.stockOut,
          quantity: quantity,
          at: at,
        ),
      );
    }
  }

  return ScaleSeedPlan(
    categories: categories,
    products: products,
    mutations: mutations,
  );
}

/// Cost price as a 55–80% fraction of sell price, so every seeded product
/// turns a positive but varying margin.
double _costPriceFor(SeedProduct product, Random random) {
  final fraction = 0.55 + random.nextInt(26) / 100;
  return (product.sellPrice * fraction).roundToDouble();
}

List<SeedCategory> _buildCategories() {
  final categories = <SeedCategory>[];
  var index = 0;
  for (final entry in _categoryTree.entries) {
    final rootIndex = index++;
    categories.add(SeedCategory(index: rootIndex, name: entry.key));
    for (final child in entry.value) {
      categories.add(
        SeedCategory(index: index++, name: child, parentIndex: rootIndex),
      );
    }
  }
  return categories;
}

/// The profit the app *must* report for [plan] over all time, derived by
/// replaying the plan through the same pricing rules the app uses.
///
/// Every stock-out here resolves both prices (each product is opened by a
/// stock-in carrying a cost price before it can be sold), so unlike the
/// app's general case there is no "unresolvable row" branch to mirror —
/// which is exactly what makes this a usable cross-check: any mutation the
/// app drops shows up as a mismatch.
ExpectedProfit expectedProfitFor(ScaleSeedPlan plan) {
  final stock = <int, double>{for (final p in plan.products) p.index: 0};
  final avgCost = <int, double?>{for (final p in plan.products) p.index: null};

  var totalRevenue = 0.0;
  var totalCost = 0.0;
  var quantitySold = 0.0;
  final soldProducts = <int>{};

  for (final mutation in plan.mutations) {
    final index = mutation.productIndex;
    final product = plan.products[index];
    final currentStock = stock[index]!;

    switch (mutation.type) {
      case SeedMutationType.stockIn:
        final incomingCost = mutation.costPricePerUnit;
        if (incomingCost != null) {
          // Same weighted average as HppCalculator.calculateNewAverage,
          // including its "no old stock means take the incoming price
          // outright" branch.
          avgCost[index] = currentStock <= 0
              ? incomingCost
              : ((currentStock * (avgCost[index] ?? 0)) +
                      (mutation.quantity * incomingCost)) /
                  (currentStock + mutation.quantity);
        }
        stock[index] = currentStock + mutation.quantity;

      case SeedMutationType.stockOut:
        stock[index] = currentStock - mutation.quantity;
        // The snapshot a stock-out carries is the HPP as it stands right
        // now — unchanged by the sale itself.
        final cost = avgCost[index];
        if (cost == null) continue;
        totalRevenue += product.sellPrice * mutation.quantity;
        totalCost += cost * mutation.quantity;
        quantitySold += mutation.quantity;
        soldProducts.add(index);
    }
  }

  return ExpectedProfit(
    totalRevenue: totalRevenue,
    totalCost: totalCost,
    quantitySold: quantitySold,
    productsSold: soldProducts.length,
    finalStockByProductIndex: stock,
  );
}

/// Product indexes that end at or below their own `minStockThreshold` —
/// exactly the set `NotificationService.executeCriticalStockAlertSlot`
/// must name, computed from the plan rather than from the database.
Set<int> expectedCriticalProductIndexes(
  ScaleSeedPlan plan,
  ExpectedProfit expected,
) {
  return {
    for (final product in plan.products)
      if (expected.finalStockByProductIndex[product.index]! <=
          product.minStockThreshold)
        product.index,
  };
}

/// Thrown by [assertSafeSeedDirectory] when a seed target would land on
/// the production database.
class UnsafeSeedDirectoryError extends Error {
  UnsafeSeedDirectoryError(this.message);

  final String message;

  @override
  String toString() => 'UnsafeSeedDirectoryError: $message';
}

/// Refuses any seed directory that is — or sits inside — the app's real
/// documents directory, which is where `IsarService.open()` puts the
/// production database.
///
/// This is the hard stop that makes the scale test safe to run on a phone
/// that has the real app installed: the seeder calls it with the directory
/// it is about to open *before* opening anything, so a mistake fails loudly
/// instead of quietly writing 1000 rows into the shop's real ledger.
///
/// Comparison is on normalised, separator-terminated paths so
/// `/data/.../documents_seed` isn't mistaken for a child of
/// `/data/.../documents`.
void assertSafeSeedDirectory({
  required String seedDirectory,
  required String productionDirectory,
}) {
  final seed = _normalise(seedDirectory);
  final production = _normalise(productionDirectory);

  if (seed == production) {
    throw UnsafeSeedDirectoryError(
      'Refusing to seed into the production database directory '
      '($seedDirectory).',
    );
  }
  if (seed.startsWith(production)) {
    throw UnsafeSeedDirectoryError(
      'Refusing to seed into $seedDirectory: it is inside the production '
      'database directory ($productionDirectory).',
    );
  }
}

/// Trailing-separator-terminated form, so prefix comparison can only match
/// on a whole path segment.
String _normalise(String path) {
  var normalised = path.replaceAll('\\', '/');
  while (normalised.endsWith('/')) {
    normalised = normalised.substring(0, normalised.length - 1);
  }
  return '$normalised/';
}
